### ISSUE TITLE
Download button is not shown anymore

### ISSUE THREAD

**Issue by dSeeder** [Lekensteyn/apk-downloader#9] opened 2014-02-09 18:44 UTC
If I am not wrong, it stopped working. No icon is showing to download. Tried signing in and out, but no luck. Is it just me or everyone?

**Comment by dSeeder** [comment] 2014-02-10 07:36
using latest APK Downloader and Chrome Version 32.0.1700.107 m.

**Comment by Lekensteyn** [comment] 2014-02-10 10:44
Confirmed for Chromium 32.0.1700.107, also reported by mail and on XDA. Will investigate.

**Comment by dSeeder** [comment] 2014-02-10 18:22
Thanks. I hope you will find a resolution fast. Hats off for this great work.

**Comment by Lekensteyn** [comment] 2014-02-11 16:59
It should be fixed now, if not, please re-open with details!

**Closed as completed by Lekensteyn** 2014-02-11 16:59 UTC
Labels: bug

**Comment by dSeeder** [comment] 2014-02-11 18:54
Thank you. It's working now. So what was the cause it was giving an error?

**Comment by Lekensteyn** [comment] 2014-02-11 20:00
See b3c3eb33c38ec4c4476a0e14f7567b845aa78e05

**Comment by dSeeder** [comment] 2014-02-11 20:21
So the Price was the culprit as usual. How you debugged it? I mean, how you get to know that the problem was there. Curious!

**Comment by Lekensteyn** [comment] 2014-02-11 20:24
The issue was spotted by opening the Console for the background page ("Developer mode" must be turned on for the option to get visible on the Extensions page). When the page gets loaded, a message was printed to the console that the icon is not made visible.

That made clear that the breakage was not caused by Chrome API changes. Upon further inspection, it became clear that the previous condition (empty value) was not valid anymore.

**Comment by dSeeder** [comment] 2014-02-11 20:35
Are you using Eclipse?

**Comment by Lekensteyn** [comment] 2014-02-11 20:40
For APK Downloader, I just use vim. I use Eclipse for Android development with Java.

**Comment by dSeeder** [comment] 2014-02-11 20:42
Can vim show runtime errors? What kind of apps you develop. Can I see some? :)

**Comment by Lekensteyn** [comment] 2014-02-11 20:55
I use https://github.com/scrooloose/syntastic (installed via [Vundle](https://github.com/gmarik/Vundle.vim)) for catching (syntax) errors and warnings in vim. My Android app development has so far only been limited to uni assignments and an unpublished app for capturing wireless traffic.

I really need to spend more time on developing Android apps, but I keep finding other projects that are more interesting ;)

**Comment by dSeeder** [comment] 2014-02-11 21:13
Ha Ha. Well then send me the APK. I have a friend who will love to publish your APK on her site. :)

**Comment by Lekensteyn** [comment] 2014-02-11 21:45
I can publish the APK on my site if I want, but I don't since it is not polished and required a framework and a kernel patch for proper privileges.
